### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by dyanakiev** [CoolV1994/Minecraft-Server-Script#1]
-bash: /etc/init.d/minecraft: /bin/bash^M: bad interpreter: No such file or directory

.ln: failed to create symbolic link ‘/etc/init.d/minecraft’: File exists

**Comment by dyanakiev** [comment]
Fixed...
open vi server.sh
then :set fileformat=unix 
:+1:

**Comment by CoolV1994** [comment]
Thanks for reporting and fixing this issue.
